openapi: 3.0.0
info:
  title: API utilisateurs
  version: 1.0.0

paths:
  /users:
    get:
      summary: Obtenir liste d'utilisateurs
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: size
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: OK - liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Alice
                    email:
                      type: string
                      example: alice@example.com
        '400':
          description: Mauvais paramètres
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad types for provided query parameters
