openapi: 3.0.3
info:
  title: Exercise 2 - Home
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /home:
    get:
      responses:
        200:
          description: Welcome HTML page
          content:
            text/html:
              schema:
                type: string
                example: |
                  <html><body><h1>Welcome home!</h1></body></html>
