openapi: 3.0.3
info:
  title: Exercise 3 - Create Posts
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /posts:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  author:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  creation_datetime:
                    type: string
                    format: date-time
      responses:
        201:
          description: List of new posts with existing posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    author:
                      type: string
                    title:
                      type: string
                    content:
                      type: string
                    creation_datetime:
                      type: string
                      format: date-time
