openapi: 3.0.3
info:
  title: Exercise 4 - List Posts
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /posts:
    get:
      responses:
        200:
          description: List of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    author:
                      type: string
                    title:
                      type: string
                    content:
                      type: string
                    creation_datetime:
                      type: string
                      format: date-time
