openapi: 3.0.3
info:
  title: Exercise 5 - Update or Create Posts
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /posts:
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  author:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  creation_datetime:
                    type: string
                    format: date-time
      responses:
        201:
          description: Updated list of posts (insert or update)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    author:
                      type: string
                    title:
                      type: string
                    content:
                      type: string
                    creation_datetime:
                      type: string
                      format: date-time
